version: '3.8'

services:

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - .env

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml
      - ./registry/htpasswd:/etc/docker/registry/htpasswd
    restart: always

volumes:
  jenkins_data:
  registry_data: